CREATE TABLE dbo.Jobs
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Jobs PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	PluginId INT NOT NULL CONSTRAINT FK_Jobs_PluginId FOREIGN KEY REFERENCES dbo.Plugins(Id),
	VersionId INT NULL CONSTRAINT FK_Jobs_VersionId FOREIGN KEY REFERENCES dbo.Versions(Id),
	UpdateUserId INT NULL CONSTRAINT FK_Jobs_UpdateUserId FOREIGN KEY REFERENCES dbo.Users(Id),
	CreateUserId INT NULL CONSTRAINT FK_Jobs_CreateUserId FOREIGN KEY REFERENCES dbo.Users(Id),	
	UpdateDate DATETIME2(0) NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Jobs_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_Jobs_Name UNIQUE ([Name])
)
