CREATE TABLE dbo.Nodes
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Nodes PRIMARY KEY,
	UUID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Nodes_UUID DEFAULT NEWID(),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	FQDN NVARCHAR(255) NOT NULL,
	Scheme NVARCHAR(255) NOT NULL,
	IsBehindProxy BIT NOT NULL,
	IsEnabled BIT NOT NULL,
	AccessToken UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Nodes_AccessToken DEFAULT NEWID(),
	CONSTRAINT UK_Nodes_UUID UNIQUE (UUID),
	CONSTRAINT UK_Nodes_Name UNIQUE ([Name])
)
