CREATE TABLE dbo.Users
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Users PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Role] TINYINT NOT NULL,
	AuthenticationType TINYINT NOT NULL,
	PasswordHash NVARCHAR(128) NULL,
	LastLoginDate DATETIME2(0) NULL,
	UpdateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Users_UpdateDate DEFAULT SYSDATETIME(),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Users_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_Users_Name UNIQUE ([Name])
)
