CREATE TABLE dbo.UserSessions
(
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_UserSessions_Id DEFAULT NEWSEQUENTIALID(),
	UserId INT NOT NULL CONSTRAINT FK_UserSessions_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	AuthenticationMethod VARCHAR(255) NOT NULL,
	AuthenticationScheme VARCHAR(255) NOT NULL,
	HostName NVARCHAR(255) NULL,
	[ExpireDate] DATETIME2(0) NOT NULL,
	RevokeDate DATETIME2(0) NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_UserSessions_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT PK_UserSessions PRIMARY KEY (Id),
	INDEX IDX_UserId (UserId)
)