CREATE TABLE dbo.VersionUploads
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_VersionUploads PRIMARY KEY,
	UserId INT NOT NULL CONSTRAINT FK_VersionUploads_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	[FileName] NVARCHAR(255) NOT NULL,
	ContentType NVARCHAR(255) NULL,
	Content VARBINARY(MAX) NOT NULL,
	ContentLength BIGINT NOT NULL,
	LastModified DATETIME2(0) NULL,
	NodeId INT NULL CONSTRAINT FK_VersionUploads_NodeId FOREIGN KEY REFERENCES dbo.Nodes(Id),
	[Status] TINYINT NOT NULL CONSTRAINT DF_VersionUploads_Status DEFAULT 0,
	PackageId NVARCHAR(255) NULL,
	PackageVersion NVARCHAR(255) NULL,
	ErrorMessage NVARCHAR(MAX) NULL,
	ProcessingStartDate DATETIME2(0) NULL,
	ProcessingEndDate DATETIME2(0) NULL,
	VersionId INT NULL CONSTRAINT FK_VersionUploads_VersionId FOREIGN KEY REFERENCES dbo.Versions(Id),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_VersionUploads_CreateDate DEFAULT SYSDATETIME()
)