CREATE PROCEDURE dbo.RevokeUserSession
	@SessionId UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	IF NOT EXISTS(SELECT * FROM dbo.UserSessions WHERE Id = @SessionId)
	BEGIN
		RETURN 1;
	END

	UPDATE dbo.UserSessions SET RevokeDate = SYSDATETIME() WHERE Id = @SessionId;
END;
