CREATE TABLE dbo.Plugins
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Plugins PRIMARY KEY,
	PackageId VARCHAR(255) NOT NULL CONSTRAINT UK_Plugins UNIQUE,
	Name NVARCHAR(255) NOT NULL,
	Description NVARCHAR(2000) NULL,
	Author NVARCHAR(255) NOT NULL,
	CreateUserId INT NOT NULL CONSTRAINT FK_Plugins_CreateUserId FOREIGN KEY REFERENCES dbo.Users(Id),	
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Plugins_CreateDate DEFAULT SYSDATETIME(),
	UpdateUserId INT NOT NULL CONSTRAINT FK_Plugins_UpdateUserId FOREIGN KEY REFERENCES dbo.Users(Id),
	UpdateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Plugins_UpdateDate DEFAULT SYSDATETIME()	
)
