CREATE TABLE dbo.UserPlugins
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_UserPlugins PRIMARY KEY,
	UserId INT NOT NULL CONSTRAINT FK_UserPlugins_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	PluginId INT NOT NULL CONSTRAINT FK_UserPlugins_PluginId FOREIGN KEY REFERENCES dbo.Plugins(Id),
	CreateUserId INT NOT NULL CONSTRAINT FK_UserPlugins_CreateUserId FOREIGN KEY REFERENCES dbo.Users(Id),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_UserPlugins_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_UserPlugins UNIQUE (UserId, PluginId)
)
